wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.7.10
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1710480686.33192
    t:
      1:
      - 1
      - 41
      - 55
      - 79
      - 80
      2:
      - 1
      - 41
      - 55
      - 79
      - 80
      3:
      - 23
      4: 3.7.10
      5: 0.16.3
      8:
      - 6
      13: linux-x86_64
